require "dimaportenko.options"
require "dimaportenko.lazy"
require "dimaportenko.keymaps"
require "dimaportenko.colorscheme"
require "dimaportenko.cmp"
require "dimaportenko.lsp"
require "dimaportenko.telescope"
require "dimaportenko.treesitter"
require "dimaportenko.autopairs"
require "dimaportenko.comment"
require "dimaportenko.gitsigns"
require "dimaportenko.nvim-tree"
require "dimaportenko.bufferline"
require "dimaportenko.toggleterm"
require "dimaportenko.lualine"
-- require "dimaportenko.prettier"
require "dimaportenko.autocmd"
require "dimaportenko.globals"
require "dimaportenko.rntools"
require "dimaportenko.custom"
require "dimaportenko.simulators"
require "dimaportenko.dap"

require "dimaportenko.rust-tools"
